export const DEFAULT_BANKS = [
    "000 — Banco Bankpar S.A.",
    "001 — Banco do Brasil S.A.",
    "003 — Banco da Amazônia S.A.",
    "004 — Banco do Nordeste do Brasil S.A.",
    "007 — BNDES (Banco Nacional Do Desenvolvimento Social)",
    "010 — CREDICOAMO (Crédito Rural Cooperativa)",
    "011 — C.Suisse Hedging-Griffo Cv S.A (Credit Suisse)",
    "012 — Banco Standard de Investimentos S.A.",
    "014 — Natixis Brasil S.A. Banco Múltiplo",
    "015 — UBS Brasil Cctvm S.A.",
    "016 — Ccm Desp Trâns SC E RS",
    "017 — Bny Mellon Banco S.A.",
    "018 — Banco Tricury S.A.",
    "019 — Banco Azteca do Brasil S.A.",
    "021 — BANESTES S.A. (Banco do Estado do Espírito Santo)",
    "024 — Banco de Pernambuco S.A. (BANDEPE)",
    "025 — Banco Alfa S.A.",
    "029 — Banco Banerj S.A.",
    "031 — Banco Beg S.A.",
    "033 — Banco Santander (Brasil) S.A.",
    "036 — Banco Bradesco BBI S.A.",
    "037 — Banco do Estado do Pará S.A.",
    "039 — Banco do Estado do Piauí S.A. (BEP)",
    "040 — Banco Cargill S.A.",
    "041 — Banco do Estado do Rio Grande do Sul S.A.",
    "044 — Banco BVA S.A.",
    "045 — Banco Opportunity S.A.",
    "047 — Banco do Estado de Sergipe S.A.",
    "060 — Confidence Corretora de Câmbio S.A.",
    "062 — Hipercard Banco Múltiplo S.A.",
    "063 — Banco Ibi S.A. Banco Múltiplo",
    "064 — Goldman Sachs do Brasil Banco Múltiplo S.A.",
    "065 — Banco Bracce S.A.",
    "066 — Banco Morgan Stanley S.A.",
    "069 — BPN Brasil Banco Múltiplo S.A.",
    "070 — BRB (Banco de Brasília S.A.)",
    "072 — Banco Rural Mais S.A.",
    "073 — BB Banco Popular do Brasil S.A.",
    "074 — Banco J. Safra S.A.",
    "075 — Banco CR2 S.A.",
    "076 — Banco KDB S.A.",
    "077 — Banco Intermedium S.A.",
    "078 — BES Investimento do Brasil S.A. (Banco de Investimento)",
    "079 — Banco Original do Agronegócio S.A.",
    "080 — B&T Cc Ltda",
    "081 — Banco Seguro S.A.",
    "081-7 — Concórdia Banco S.A.",
    "082 — Banco Topázio S.A.",
    "083 — Banco da China Brasil S.A.",
    "084 — Unicred Norte do Paraná",
    "085 — Cooperativa Central de Crédito Urbano (CECRED)",
    "086 — OBOE Crédito Financiamento e Investimento S.A.",
    "087 — Cooperativa Unicred Central Santa Catarina",
    "088 — Banco Randon S.A.",
    "089 — Cooperativa de Crédito Rural da Região de Mogiana",
    "091 — Unicred Central do Rio Grande do Sul",
    "092 — Brickell S.A. Crédito, financiamento e Investimento",
    "093 — PóloCred Scmepp Ltda",
    "094 — Banco Finaxis",
    "094-2 — Banco Petra S.A.",
    "095 — Travelex Banco de Câmbio S.A..",
    "096 — Banco BM&F de Serviços de Liquidação e Custódia S.A",
    "097 — Cooperativa Central de Crédito Noroeste Brasileiro Ltda.",
    "098 — Credialiança Ccr",
    "098-1 — Credicorol Cooperativa de Crédito Rural",
    "099 — Uniprime Central Ccc Ltda",
    "099-x — Cooperativa Central de Economia e Credito Mutuo das Unicreds",
    "100 — Planner Corretora de Valores S.A.",
    "101 — Renascença Dtvm Ltda",
    "102 — XP Investimentos S.A.",
    "104 — Caixa Econômica Federal",
    "105 — Lecca Cfi S.A.",
    "107 — Banco BBM S.A.",
    "108 — Portocred S.A.",
    "111 — Banco Oliveira Trust Dtvm S.A.",
    "113 — Magliano S.A.",
    "114 — Central Cooperativa de Crédito no Estado do Espírito Santo",
    "117 — Advanced Cc Ltda",
    "118 — Standard Chartered Bi S.A.",
    "119 — Banco Western Union do Brasil S.A.",
    "120 — Banco Rodobens S.A.",
    "121 — Banco Agibank S.A.",
    "122 — Banco Bradesco BERJ S.A.",
    "124 — Banco Woori Bank Do Brasil S.A.",
    "125 — Brasil Plural S.A Banco",
    "126 — BR Partners Banco de Investimento S.A.",
    "127 — Codepe Cvc S.A.",
    "128 — Ms Bank S.A. Banco De Câmbio",
    "129 — UBS Brasil Bi S.A.",
    "130 — Caruana Scfi",
    "131 — Tullett Prebon Brasil Cvc Ltda",
    "132 — ICBC do Brasil Bm S.A.",
    "133 — Cresol Confederação",
    "134 — BGC Liquidez Dtvm Ltda",
    "136 — Unicred Cooperativa LTDA",
    "138 — Get Money Cc Ltda",
    "139 — Intesa Sanpaolo Brasil S.A.",
    "140 — Easynvest (Título Cv S.A.)",
    "142 — Broker Brasil Cc Ltda",
    "143 — Treviso Cc S.A.",
    "144 — Bexs Banco De Cambio S.A.",
    "145 — Levycam Ccv Ltda",
    "146 — Guitta Cc Ltda",
    "149 — Facta S.A. Cfi",
    "157 — Icap Do Brasil Ctvm Ltda",
    "159 — Casa do Crédito S.A.",
    "163 — Commerzbank Brasil S.A Banco Múltiplo",
    "168 — HSBC Finance (Brasil) S.A. (Banco Múltiplo)",
    "169 — Banco Olé Bonsucesso Consignado S.A.",
    "172 — Albatross Ccv S.A.",
    "173 — BRL Trust Dtvm Sa",
    "174 — Pernambucanas Financ S.A.",
    "177 — Guide Investimentos S.A. Corretora de Valores",
    "180 — Cm Capital Markets Cctvm Ltda",
    "182 — Dacasa Financeira S/A",
    "183 — Socred S.A.",
    "184 — Banco Itaú BBA S.A.",
    "188 — Ativa S.A Investimentos",
    "189 — HS Financeira",
    "190 — Servicoop",
    "191 — Nova Futura Ctvm Ltda",
    "194 — Parmetal Dtvm Ltda",
    "196 — Banco Fair Cc S.A.",
    "197 — Stone Pagamentos S.A.",
    "204 — Banco Bradesco Cartões S.A.",
    "208 — Banco BTG Pactual S.A.",
    "212 — Banco Matone S.A.",
    "213 — Banco Arbi S.A.",
    "214 — Banco Dibens S.A.",
    "215 — Banco Comercial e de Investimento Sudameris S.A.",
    "217 — Banco John Deere S.A.",
    "218 — Banco Bs2 S.A.",
    "222 — Banco Credit Agricole Brasil S.A.",
    "224 — Banco Fibra S.A.",
    "225 — Banco Brascan S.A.",
    "229 — Banco Cruzeiro do Sul S.A.",
    "230 — Unicard Banco Múltiplo S.A.",
    "233 — Banco GE Capital S.A.",
    "237 — Banco Bradesco S.A.",
    "241 — Banco Clássico S.A.",
    "243 — Banco Máxima S.A.",
    "246 — Banco ABC Brasil S.A.",
    "248 — Banco Boavista Interatlântico S.A.",
    "249 — Banco Investcred Unibanco S.A.",
    "250 — Banco Schahin S.A.",
    "253 — Bexs Cc S.A.",
    "254 — Paraná Banco S.A.",
    "259 — MONEYCORP Banco de Câmbio S.A.",
    "260 — Nu Pagamentos S.A (Nubank)",
    "263 — Banco Cacique S.A.",
    "265 — Banco Fator S.A.",
    "266 — Banco Cédula S.A.",
    "268 — Barigui Companhia Hipotecária",
    "269 — Hsbc Banco De Investimento",
    "270 — Sagitur Cc Ltda",
    "271 — Ib Cctvm Ltda",
    "272 — AGK Corretora de Câmbio S.A.",
    "273 — Ccr De São Miguel Do Oeste",
    "274 — MONEY PLUS Sociedade de Crédito",
    "276 — Senff S.A.",
    "278 — Genial Investimentos Cvm S.A.",
    "279 — Ccr De Primavera Do Leste",
    "280 — Avista S.A.",
    "281 — Cooperativa de Crédito Rural Coopavel",
    "283 — RB Capital Investimentos Dtvm Ltda",
    "285 — Frente Cc Ltda",
    "286 — Cooperativa de Crédito Rural de De Ouro",
    "288 — Carol Dtvm Ltda",
    "289 — DECYSEO Corretora de Câmbio LTDA.",
    "290 — PagSeguro Internet S.A.",
    "292 — BS2 Distribuidora De Títulos E Investimentos",
    "293 — Lastro Rdv Dtvm Ltda",
    "296 — VISION S.A. Corretora de Câmbio",
    "298 — Vip’s Cc Ltda",
    "299 — SOROCRED Crédito, Financiamento E Investimento S.A.",
    "300 — Banco de La Nacion Argentina",
    "301 — BPP Instituição De Pagamentos S.A.",
    "306 — PORTOPAR Distribuidora de Títulos e Valores Mobiliários",
    "307 — Terra Investimentos Distribuidora de Títulos e Valores Mobiliários",
    "309 — CAMBIONET Corretora de Câmbio LTDA.",
    "310 — VORTX Dtvm Ltda",
    "313 — AMAZÔNIA Corretora de Câmbio LTDA.",
    "315 — PI Distribuidora de Títulos e Valores Mobiliários S.A.",
    "318 — Banco BMG S.A.",
    "319 — OM Distribuidora de Títulos e Valores Mobiliários LTDA",
    "320 — Banco Industrial e Comercial S.A.",
    "322 — Cooperativa de Crédito Rural de Abelardo Luz (Sulcredi/Crediluz)",
    "323 — Mercado Pago (Conta do Mercado Livre)",
    "324 — CARTOS SOCIEDADE DE CRÉDITO DIRETO S.A.",
    "325 — Órama Distribuidora de Títulos e Valores Mobiliários S.A.",
    "326 — PARATI (Crédito, Financiamento e investimento S.A.)",
    "329 — QI Sociedade de Crédito Direto S.A.",
    "330 — Banco Bari de Investimentos e Financiamentos S.A.",
    "331 — Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.",
    "332 — Acesso Soluções de Pagamento S.A.",
    "335 — Banco Digio S.A.",
    "336 — Banco C6 S.A (C6 Bank)",
    "340 — Super Pagamentos S/A (Superdital)",
    "341 — Itaú Unibanco S.A.",
    "342 — Creditas Sociedade de Crédito Direto S.A.",
    "343 — FFA Sociedade de crédito ao Microempreendedor",
    "348 — Banco XP S/A",
    "349 — AL5 S.A. Crédito, Financiamento e Investimento",
    "350 — Cooperativa de Crédito Rural de Pequenos Agricultores",
    "352 — TORO Corretora de Títulos e Valores Mobiliários LTDA",
    "354 — NECTON Investimentos S.A.",
    "355 — ÓTIMO Sociedade de Crédito Direto S.A.",
    "356 — Banco Real S.A.",
    "359 — ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A",
    "360 — TRINUS Capital Distribuidora De Títulos E Valores Mobiliários S.A.",
    "362 — CIELO S.A.",
    "363 — SOCOPA Sociedade Corretora Paulista S.A.",
    "364 — GERENCIANET S.A.",
    "365 — SOLIDUS S.A. Corretora de Câmbio e Valores Mobiliários",
    "366 — Banco Société Générale Brasil S.A.",
    "367 — VITREO Distribuidora de Títulos e Valores Mobiliários",
    "368 — Banco CSF S.A.",
    "370 — Banco WestLB do Brasil S.A.",
    "371 — WARREN Corretora de Valores Mobiliários e Câmbio LTDA.",
    "373 — UP.P Sociedade de Empréstimo entre pessoas S.A.",
    "374 — REALIZE Crédito, Financiamento e Investimento S.A.",
    "376 — Banco J. P. Morgan S.A.",
    "377 — MS Sociedade de Crédito ao Microempreendedor e a empresa",
    "378 — BBC LEASING S.A. (Arrendamento Mercantil)",
    "379 — COOPERFORTE",
    "380 — PICPAY Serviços S.A.",
    "381 — BANCO Mercedes-Benz DO BRASIL S.A.",
    "382 — FIDÚCIA Sociedade de Crédito ao Microempreendedor",
    "383 — BOLETOBANCÁRIO.COM Tecnologia de Pagamentos LTDA.",
    "384 — Global Finanças",
    "387 — Banco Toyota do Brasil S.A.",
    "389 — Banco Mercantil do Brasil S.A.",
    "390 — BANCO GM S.A.",
    "391 — Cooperativa de Crédito Rural de IBIAM (SULCREDI/IBIAM)",
    "393 — Banco Volkswagen S.A.",
    "394 — Banco Bradesco Financiamentos S.A.",
    "396 — HUB Pagamentos S.A.",
    "397 — LISTO Sociedade de Crédito Direto S.A.",
    "399 — HSBC Bank Brasil S.A. (Banco Múltiplo)",
    "403 — CORA Sociedade de Crédito Direto S.A.",
    "404 — SUMUP Sociedade de Crédito Direto S.A.",
    "408 — BÔNUSCRED Sociedade de Crédito Direto S.A.",
    "409 — Unibanco (União de Bancos Brasileiros S.A.)",
    "412 — Banco Capital S.A.",
    "422 — Banco Safra S.A.",
    "453 — Banco Rural S.A.",
    "456 — Banco de Tokyo-Mitsubishi UFJ Brasil S.A.",
    "464 — Banco Sumitomo Mitsui Brasileiro S.A.",
    "473 — Banco Caixa Geral (Brasil S.A.)",
    "477 — Citibank N.A.",
    "479 — Banco ItaúBank S.A",
    "487 — Deutsche Bank S.A. (Banco Alemão)",
    "488 — JPMorgan Chase Bank",
    "492 — ING Bank N.V.",
    "494 — Banco de La Republica Oriental del Uruguay",
    "495 — Banco de La Provincia de Buenos Aires",
    "505 — Banco Credit Suisse (Brasil) S.A.",
    "545 — Senso Ccvm S.A.",
    "600 — Banco Luso Brasileiro S.A.",
    "604 — Banco Industrial do Brasil S.A.",
    "610 — Banco VR S.A.",
    "611 — Banco Paulista S.A.",
    "612 — Banco Guanabara S.A.",
    "613 — Banco Pecúnia S.A.",
    "623 — Banco Panamericano S.A.",
    "626 — Banco Ficsa S.A.",
    "630 — Banco Intercap S.A.",
    "633 — Banco Rendimento S.A.",
    "634 — Banco Triângulo S.A.",
    "637 — Banco Sofisa S.A.",
    "638 — Banco Prosper S.A.",
    "641 — Banco Alvorada S.A.",
    "643 — Banco Pine S.A.",
    "652 — Itaú Unibanco Holding S.A.",
    "653 — Banco Indusval S.A.",
    "654 — Banco A.J.Renner S.A.",
    "655 — Banco Votorantim S.A.",
    "707 — Banco Daycoval S.A.",
    "712 — Banco Ourinvest S.A.",
    "719 — Banif-Banco Internacional do Funchal (Brasil)S.A.",
    "721 — Banco Credibel S.A.",
    "724 — Banco Porto Seguro S.A.",
    "734 — Banco Gerdau S.A.",
    "735 — Banco Pottencial S.A.",
    "738 — Banco Morada S.A.",
    "739 — Banco BGN S.A.",
    "740 — Banco Barclays S.A.",
    "741 — Banco Ribeirão Preto S.A.",
    "743 — Banco Semear S.A.",
    "744 — BankBoston N.A.",
    "745 — Banco Citibank S.A.",
    "746 — Banco Modal S.A.",
    "747 — Banco Rabobank International Brasil S.A.",
    "748 — Banco Cooperativo Sicredi S.A.",
    "749 — Banco Simples S.A.",
    "751 — Dresdner Bank Brasil S.A. (Banco Múltiplo)",
    "752 — Banco BNP Paribas Brasil S.A.",
    "753 — NBC Bank Brasil S.A. (Banco Múltiplo)",
    "754 — Banco Sistema S.A.",
    "755 — Bank of America Merrill Lynch Banco Múltiplo S.A.",
    "756 — Banco Cooperativo do Brasil S.A. – BANCOOB",
    "757 — Banco KEB do Brasil S.A.",
    "M03 — Banco Fiat S.A.",
    "M06 — Banco de Lage Landen Brasil S.A.",
    "M07 — Banco GMAC S.A.",
    "M08 — Banco Citicard S.A.",
    "M09 — Banco Itaucred Financiamentos S.A.",
    "M10 — Banco Moneo S.A.",
    "M11 — Banco IBM S.A.",
    "M12 — Banco Maxinvest S.A.",
    "M13 — Banco Tricury S.A.",
    "M14 — Banco Volkswagen S.A.",
    "M15 — Banco BRJ S.A.",
    "M16 — Banco Rodobens S.A.",
    "M17 — Banco Ourinvest S.A.",
    "M18 — Banco Ford S.A.",
    "M19 — Banco CNH Capital S.A.",
    "M20 — Banco Toyota do Brasil S.A.",
    "M21 — Banco Daimlerchrysler S.A.",
    "M22 — Banco Honda S.A.",
    "M23 — Banco Volvo (Brasil) S.A.",
    "M24 — Banco PSA Finance Brasil S.A."
];
