export const DEFAULT_AVATAR = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' fill='%23ff5a00'/><clipPath id='circle-clip'><circle cx='50' cy='50' r='38'/></clipPath><circle cx='50' cy='50' r='38' fill='%2300205b'/><g clip-path='url(%23circle-clip)'><circle cx='50' cy='42' r='13' fill='none' stroke='%23ffffff' stroke-width='3.5' stroke-linecap='round'/><path d='M41,53.5 L41,60' fill='none' stroke='%23ffffff' stroke-width='3' stroke-linecap='round'/><path d='M59,53.5 L59,60' fill='none' stroke='%23ffffff' stroke-width='3' stroke-linecap='round'/><path d='M22,70 C22,60 30,58 40.5,58 L40.5,62 L50,69 L59.5,62 L59.5,58 C70,58 78,60 78,70' fill='none' stroke='%23ff5a00' stroke-width='3.5' stroke-linecap='round' stroke-linejoin='round'/></g></svg>";

export const getUserAvatar = (img) => {
    if (!img || typeof img !== 'string' || img === 'profile/default-avatar.png' || !img.includes || img.includes('default-avatar')) {
        return DEFAULT_AVATAR;
    }
    return img;
};

export const users = [
    {
        id: 99,
        name: 'ADMINISTRADOR',
        displayName: 'Admin',
        role: 'Administrador',
        img: 'profile/default-avatar.png',
        avatarFallback: 'A',
        status: 'Ativo',
        accessLevel: 'Administrador',
        pin: '0000',
        password: 'admin',
        phone: '',
        email: 'admin@bellaitalia.com.br',
        permissions: {
            entrada: true, saida: true, perdas: true, editar: true, relatorios: true,
            config: true, excluir: true, sendMsg: true, sendNotif: true, receiveNotif: true,
            sendAlert: true, approveRequests: true, requestItems: true, sendDocs: true,
            viewDocs: true, supplierView: true, supplierCreate: true, supplierEdit: true,
            supplierBlock: true, supplierDelete: true, chkCreate: true, chkAnswer: true,
            chkApprove: true, chkReports: true
        }
    },
    {
        id: 1,
        name: 'Rafael Mendes',
        displayName: 'Rafael',
        role: 'Gerente de Pizzaria',
        img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&h=150&q=80',
        avatarFallback: 'R',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1001',
        password: '',
        phone: '(11) 98765-1111',
        email: 'rafael@bellaitalia.com.br',
        permissions: {
            entrada: true, saida: true, perdas: true, editar: true, relatorios: true,
            config: true, excluir: true, sendMsg: true, sendNotif: true, receiveNotif: true,
            sendAlert: true, approveRequests: true, requestItems: true, sendDocs: true,
            viewDocs: true, supplierView: true, supplierCreate: true, supplierEdit: true,
            supplierBlock: true, supplierDelete: true, chkCreate: true, chkAnswer: true,
            chkApprove: true, chkReports: true
        }
    },
    {
        id: 2,
        name: 'Gustavo Santos',
        displayName: 'Gustavo',
        role: 'Gerente de Pizzaria',
        img: 'profile/default-avatar.png',
        avatarFallback: 'G',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1002',
        password: '',
        phone: '(11) 98765-2222',
        email: 'gustavo@bellaitalia.com.br',
        permissions: {
            entrada: true, saida: true, perdas: true, editar: true, relatorios: true,
            config: true, excluir: true, sendMsg: true, sendNotif: true, receiveNotif: true,
            sendAlert: true, approveRequests: true, requestItems: true, sendDocs: true,
            viewDocs: true, supplierView: true, supplierCreate: true, supplierEdit: true,
            supplierBlock: true, supplierDelete: true, chkCreate: true, chkAnswer: true,
            chkApprove: true, chkReports: true
        }
    },
    {
        id: 3,
        name: 'Bruno Silva',
        displayName: 'Bruno',
        role: 'Supervisor de Turno',
        img: 'profile/default-avatar.png',
        avatarFallback: 'B',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1003',
        password: '',
        phone: '(11) 98765-3333',
        email: 'bruno@bellaitalia.com.br',
        permissions: {
            entrada: true, saida: true, perdas: true, editar: true, relatorios: true,
            config: false, excluir: false, sendMsg: true, sendNotif: true, receiveNotif: true,
            sendAlert: true, approveRequests: true, requestItems: true, sendDocs: true,
            viewDocs: true, supplierView: true, supplierCreate: true, supplierEdit: true,
            supplierBlock: false, supplierDelete: false, chkCreate: true, chkAnswer: true,
            chkApprove: true, chkReports: true
        }
    },
    {
        id: 4,
        name: 'Camila Costa',
        displayName: 'Camila',
        role: 'Supervisor de Turno',
        img: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&h=150&q=80',
        avatarFallback: 'Ca',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1004',
        password: '',
        phone: '(11) 98765-4444',
        email: 'camila@bellaitalia.com.br',
        permissions: {
            entrada: true, saida: true, perdas: true, editar: true, relatorios: true,
            config: false, excluir: false, sendMsg: true, sendNotif: true, receiveNotif: true,
            sendAlert: true, approveRequests: true, requestItems: true, sendDocs: true,
            viewDocs: true, supplierView: true, supplierCreate: true, supplierEdit: true,
            supplierBlock: false, supplierDelete: false, chkCreate: true, chkAnswer: true,
            chkApprove: true, chkReports: true
        }
    },
    {
        id: 5,
        name: 'Anderson Silva',
        displayName: 'Anderson',
        role: 'Pizzaiolo',
        img: 'profile/default-avatar.png',
        avatarFallback: 'An',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1005',
        password: '',
        phone: '(11) 98765-5555',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: true, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 6,
        name: 'Leandro Souza',
        displayName: 'Leandro',
        role: 'Pizzaiolo',
        img: 'profile/default-avatar.png',
        avatarFallback: 'L',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1006',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: true, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 7,
        name: 'Thiago Santos',
        displayName: 'Thiago',
        role: 'Pizzaiolo',
        img: 'profile/default-avatar.png',
        avatarFallback: 'T',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1007',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: true, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 8,
        name: 'Rodrigo Lima',
        displayName: 'Rodrigo',
        role: 'Auxiliar de Pizzaiolo',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Ro',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1008',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: true, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 9,
        name: 'Douglas Costa',
        displayName: 'Douglas',
        role: 'Auxiliar de Pizzaiolo',
        img: 'profile/default-avatar.png',
        avatarFallback: 'D',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1009',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: true, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 10,
        name: 'Fernanda Dias',
        displayName: 'Fernanda',
        role: 'Cozinheiro',
        img: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&h=150&q=80',
        avatarFallback: 'Fe',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1010',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: true, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 11,
        name: 'Juliana Ramos',
        displayName: 'Juliana',
        role: 'Cozinheiro',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Ju',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1011',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: true, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 12,
        name: 'João Silva',
        displayName: 'João',
        role: 'Auxiliar de Cozinha',
        img: 'profile/default-avatar.png',
        avatarFallback: 'J',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1012',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 13,
        name: 'Felipe Santos',
        displayName: 'Felipe',
        role: 'Auxiliar de Cozinha',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Fl',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1013',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 14,
        name: 'Daniel Costa',
        displayName: 'Daniel',
        role: 'Auxiliar de Cozinha',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Da',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1014',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 15,
        name: 'André Costa',
        displayName: 'André',
        role: 'Maître',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Ad',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1015',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: true, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 16,
        name: 'Ricardo Alves',
        displayName: 'Ricardo',
        role: 'Garçom',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Ri',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1016',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: true, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 17,
        name: 'Pedro Santos',
        displayName: 'Pedro',
        role: 'Garçom',
        img: 'profile/default-avatar.png',
        avatarFallback: 'P',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1017',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: true, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 18,
        name: 'Gabriel Lima',
        displayName: 'Gabriel',
        role: 'Garçom',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Gb',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1018',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: true, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 19,
        name: 'Vinícius Souza',
        displayName: 'Vinícius',
        role: 'Garçom',
        img: 'profile/default-avatar.png',
        avatarFallback: 'V',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1019',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: true, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 20,
        name: 'Carlos Santos',
        displayName: 'Carlos',
        role: 'Cumim',
        img: 'profile/default-avatar.png',
        avatarFallback: 'C',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1020',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 21,
        name: 'Sandra Xavier',
        displayName: 'Sandra',
        role: 'Atendente de Delivery',
        img: 'profile/default-avatar.png',
        avatarFallback: 'S',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1021',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: true, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 22,
        name: 'Aline Ramos',
        displayName: 'Aline',
        role: 'Atendente de Delivery',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Al',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1022',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: true, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: true, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 23,
        name: 'Mateus Silva',
        displayName: 'Mateus',
        role: 'Entregador',
        img: 'profile/default-avatar.png',
        avatarFallback: 'M',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1023',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: false, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 24,
        name: 'Lucas Mendes',
        displayName: 'Lucas',
        role: 'Entregador',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Lc',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1024',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: false, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 25,
        name: 'Rafael Oliveira',
        displayName: 'Rafael O.',
        role: 'Entregador',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Ro',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1025',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: false, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 26,
        name: 'Renato Oliveira',
        displayName: 'Renato',
        role: 'Estoquista',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Rn',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1026',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: true, saida: true, perdas: true, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: false, supplierView: true, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 27,
        name: 'Roberto Lima',
        displayName: 'Roberto',
        role: 'Comprador',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Rb',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1027',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: true, saida: true, perdas: true, editar: true, relatorios: false,
            config: false, excluir: false, sendMsg: true, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: true, supplierView: true, supplierCreate: true, supplierEdit: true,
            supplierBlock: false, supplierDelete: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 28,
        name: 'Maria Santos',
        displayName: 'Maria',
        role: 'Auxiliar de Limpeza',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Ma',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1028',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: false, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 29,
        name: 'Luciana Costa',
        displayName: 'Luciana',
        role: 'Auxiliar de Limpeza',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Lu',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1029',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: false, saida: false, perdas: false, editar: false, relatorios: false,
            config: false, excluir: false, sendMsg: false, sendNotif: false, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: false, sendDocs: true,
            viewDocs: false, supplierView: false, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    },
    {
        id: 30,
        name: 'Patrícia Melo',
        displayName: 'Patrícia',
        role: 'Analista Administrativo',
        img: 'profile/default-avatar.png',
        avatarFallback: 'Pt',
        status: 'Ativo',
        accessLevel: 'Colaborador',
        pin: '1030',
        password: '',
        phone: '',
        email: '',
        permissions: {
            entrada: true, saida: true, perdas: false, editar: true, relatorios: true,
            config: false, excluir: false, sendMsg: true, sendNotif: true, receiveNotif: true,
            sendAlert: false, approveRequests: false, requestItems: true, sendDocs: true,
            viewDocs: true, supplierView: true, chkCreate: false, chkAnswer: true,
            chkApprove: false, chkReports: false
        }
    }
];

export const categories = [
    { id: 1, name: "FARINHAS E MASSAS", icon: "fa-wheat-awn", color: "color-yellow", desc: "Farinhas, fermentos e bases de massa.", status: "Ativo" },
    { id: 2, name: "LATICÍNIOS", icon: "fa-cheese", color: "color-blue", desc: "Queijos, requeijão, creme de leite e derivados.", status: "Ativo" },
    { id: 3, name: "MOLHOS E CONDIMENTOS", icon: "fa-bottle-droplet", color: "color-orange", desc: "Molho de tomate pelati, azeites e conservas.", status: "Ativo" },
    { id: 4, name: "CARNES E FRIOS", icon: "fa-drumstick-bite", color: "color-red", desc: "Calabresa, presunto, bacon, frango e embutidos.", status: "Ativo" },
    { id: 5, name: "VEGETAIS E HORTIFRUTI", icon: "fa-carrot", color: "color-green", desc: "Tomates, cebolas, rúcula, manjericão e frescos.", status: "Ativo" },
    { id: 6, name: "BEBIDAS", icon: "fa-wine-bottle", color: "color-teal", desc: "Água, refrigerantes e cervejas geladas.", status: "Ativo" },
    { id: 7, name: "EMBALAGENS", icon: "fa-box", color: "color-brown", desc: "Caixas de pizza 35cm/40cm e sacolas delivery.", status: "Ativo" },
    { id: 8, name: "HIGIENE E OPERACIONAL", icon: "fa-spray-can", color: "color-indigo", desc: "Produtos de limpeza, sanitizantes e descartáveis.", status: "Ativo" }
];

export const saleProductCategories = [
    { id: 1, name: "PIZZAS", icon: "fa-pizza-slice", color: "color-pink", desc: "Pizzas salgadas e doces assadas no forno a lenha.", status: "Ativo" },
    { id: 2, name: "BEBIDAS", icon: "fa-wine-bottle", color: "color-teal", desc: "Refrigerantes gelados, sucos e cervejas.", status: "Ativo" },
    { id: 3, name: "SOBREMESAS", icon: "fa-ice-cream", color: "color-purple", desc: "Pizzas doces e sobremesas em geral.", status: "Ativo" }
];

export const items = [];

export const products = [
    { sku: "MAS-001", name: "Farinha de Trigo Especial 00", brand: "Le 5 Stagioni", desc: "Farinha de trigo italiana tipo 00 para pizzas.", unit: "KG", stock: 150, category: "FARINHAS E MASSAS", status: "Ativo", minStock: 50, avgStock: 200, maxStock: 400 },
    { sku: "MAS-002", name: "Fermento Biológico Seco", brand: "Fermipan", desc: "Fermento biológico seco instantâneo.", unit: "KG", stock: 8, category: "FARINHAS E MASSAS", status: "Ativo", minStock: 2, avgStock: 10, maxStock: 20 },
    { sku: "LAC-001", name: "Queijo Muçarela Barra", brand: "Mantiqueira", desc: "Queijo muçarela em barra para fatiar/ralar.", unit: "KG", stock: 120, category: "LATICÍNIOS", status: "Ativo", minStock: 30, avgStock: 120, maxStock: 250, controlaProducao: true },
    { sku: "MOL-001", name: "Molho de Tomate Pelati", brand: "La Molisana", desc: "Tomate pelati italiano em conserva para molhos.", unit: "KG", stock: 65, category: "MOLHOS E CONDIMENTOS", status: "Ativo", minStock: 20, avgStock: 80, maxStock: 160 },
    { sku: "PRO-001", name: "Calabresa Defumada Inteira", brand: "Sadia", desc: "Linguiça calabresa defumada reta.", unit: "KG", stock: 45, category: "CARNES E FRIOS", status: "Ativo", minStock: 15, avgStock: 60, maxStock: 120 },
    { sku: "PRO-002", name: "Presunto Cozido Peça", brand: "Perdigão", desc: "Presunto cozido sem capa de gordura.", unit: "KG", stock: 30, category: "CARNES E FRIOS", status: "Ativo", minStock: 10, avgStock: 40, maxStock: 80 },
    { sku: "PRO-003", name: "Bacon Manta Defumado", brand: "Seara", desc: "Bacon manta defumado especial.", unit: "KG", stock: 25, category: "CARNES E FRIOS", status: "Ativo", minStock: 10, avgStock: 30, maxStock: 60 },
    { sku: "PRO-004", name: "Peito de Frango Desfiado", brand: "Copacol", desc: "Peito de frango cozido e desfiado IQF.", unit: "KG", stock: 35, category: "CARNES E FRIOS", status: "Ativo", minStock: 10, avgStock: 50, maxStock: 100 },
    { sku: "LAC-002", name: "Requeijão Culinário Scala", brand: "Scala", desc: "Requeijão cremoso tipo catupiry balde 1.5kg.", unit: "UN", stock: 25, category: "LATICÍNIOS", status: "Ativo", minStock: 5, avgStock: 20, maxStock: 40 },
    { sku: "LAC-003", name: "Queijo Parmesão Peça", brand: "Faixa Azul", desc: "Queijo parmesão tipo grana peça inteira.", unit: "KG", stock: 15, category: "LATICÍNIOS", status: "Ativo", minStock: 5, avgStock: 20, maxStock: 40 },
    { sku: "LAC-004", name: "Queijo Gorgonzola Peça", brand: "Cruzilia", desc: "Queijo azul tipo gorgonzola peça.", unit: "KG", stock: 12, category: "LATICÍNIOS", status: "Ativo", minStock: 4, avgStock: 15, maxStock: 30 },
    { sku: "LAC-005", name: "Queijo Provolone Defumado", brand: "President", desc: "Queijo provolone defumado peça.", unit: "KG", stock: 15, category: "LATICÍNIOS", status: "Ativo", minStock: 5, avgStock: 20, maxStock: 40 },
    { sku: "HOR-001", name: "Tomate Carmem Fresco", brand: "Horti-Pizza", desc: "Tomate carmem maduro selecionado.", unit: "KG", stock: 40, category: "VEGETAIS E HORTIFRUTI", status: "Ativo", minStock: 15, avgStock: 50, maxStock: 100 },
    { sku: "HOR-002", name: "Cebola Roxa", brand: "Horti-Pizza", desc: "Cebola roxa média especial.", unit: "KG", stock: 20, category: "VEGETAIS E HORTIFRUTI", status: "Ativo", minStock: 5, avgStock: 30, maxStock: 60 },
    { sku: "HOR-003", name: "Cebola Branca", brand: "Horti-Pizza", desc: "Cebola branca média especial.", unit: "KG", stock: 30, category: "VEGETAIS E HORTIFRUTI", status: "Ativo", minStock: 10, avgStock: 40, maxStock: 80 },
    { sku: "HOR-004", name: "Manjericão Fresco Maço", brand: "Horti-Pizza", desc: "Folhas de manjericão fresco maço.", unit: "UN", stock: 15, category: "VEGETAIS E HORTIFRUTI", status: "Ativo", minStock: 5, avgStock: 20, maxStock: 40 },
    { sku: "HOR-005", name: "Rúcula Fresca Maço", brand: "Horti-Pizza", desc: "Rúcula em folhas fresca maço.", unit: "UN", stock: 18, category: "VEGETAIS E HORTIFRUTI", status: "Ativo", minStock: 5, avgStock: 25, maxStock: 50 },
    { sku: "HOR-006", name: "Alho Roxo Cabeça", brand: "Horti-Pizza", desc: "Alho roxo nacional especial.", unit: "KG", stock: 10, category: "VEGETAIS E HORTIFRUTI", status: "Ativo", minStock: 3, avgStock: 15, maxStock: 30 },
    { sku: "HOR-007", name: "Azeitona Preta Inteira", brand: "Vale Fértil", desc: "Azeitona preta com caroço em balde.", unit: "KG", stock: 25, category: "VEGETAIS E HORTIFRUTI", status: "Ativo", minStock: 8, avgStock: 30, maxStock: 60 },
    { sku: "TMP-001", name: "Azeite de Oliva Extra Virgem 500ml", brand: "Andorinha", desc: "Azeite de oliva extra virgem de mesa.", unit: "UN", stock: 24, category: "MOLHOS E CONDIMENTOS", status: "Ativo", minStock: 8, avgStock: 30, maxStock: 60 },
    { sku: "TMP-002", name: "Orégano Desidratado", brand: "Kitano", desc: "Orégano em folhas secas desidratadas.", unit: "KG", stock: 5, category: "MOLHOS E CONDIMENTOS", status: "Ativo", minStock: 1, avgStock: 6, maxStock: 12 },
    { sku: "TMP-003", name: "Sal Refinado 1kg", brand: "Cisne", desc: "Sal refinado iodado culinário.", unit: "UN", stock: 10, category: "MOLHOS E CONDIMENTOS", status: "Ativo", minStock: 3, avgStock: 15, maxStock: 30 },
    { sku: "BEB-001", name: "Refrigerante Coca-Cola 2L", brand: "Coca-Cola", desc: "Refrigerante de cola garrafa 2 litros.", unit: "UN", stock: 60, category: "BEBIDAS", status: "Ativo", minStock: 20, avgStock: 80, maxStock: 160 },
    { sku: "BEB-002", name: "Refrigerante Guaraná Antarctica 2L", brand: "Antarctica", desc: "Refrigerante de guaraná garrafa 2 litros.", unit: "UN", stock: 50, category: "BEBIDAS", status: "Ativo", minStock: 15, avgStock: 60, maxStock: 120 },
    { sku: "BEB-003", name: "Cerveja Stella Artois Long Neck", brand: "Ambev", desc: "Cerveja long neck lager 330ml.", unit: "UN", stock: 120, category: "BEBIDAS", status: "Ativo", minStock: 40, avgStock: 150, maxStock: 300 },
    { sku: "BEB-004", name: "Água Mineral Sem Gás 500ml", brand: "Crystal", desc: "Água mineral sem gás garrafa 500ml.", unit: "UN", stock: 80, category: "BEBIDAS", status: "Ativo", minStock: 20, avgStock: 100, maxStock: 200 },
    { sku: "EMB-001", name: "Caixa de Pizza Oitavada 35cm", brand: "Embalagens Brasil", desc: "Caixa de pizza papelão oitavada 35cm.", unit: "UN", stock: 300, category: "EMBALAGENS", status: "Ativo", minStock: 100, avgStock: 500, maxStock: 1000 },
    { sku: "EMB-002", name: "Sacola Kraft Delivery", brand: "Embalagens Brasil", desc: "Sacola de papel kraft reforçada para delivery.", unit: "UN", stock: 250, category: "EMBALAGENS", status: "Ativo", minStock: 80, avgStock: 400, maxStock: 800 },
    { sku: "LIM-001", name: "Detergente Neutro Concentrado 5L", brand: "Clean Química", desc: "Detergente neutro galão 5 litros.", unit: "UN", stock: 15, category: "HIGIENE E OPERACIONAL", status: "Ativo", minStock: 5, avgStock: 20, maxStock: 40 },
    { sku: "LIM-002", name: "Cloro Ativo Sanitizante 5L", brand: "Clean Química", desc: "Sanitizante de cloro ativo galão 5 litros.", unit: "UN", stock: 8, category: "HIGIENE E OPERACIONAL", status: "Ativo", minStock: 2, avgStock: 10, maxStock: 20 }
];

export const suppliers = [
    {
        id: 1,
        razaoSocial: 'MOINHO CENTRAL IMPORTADORA LTDA',
        nomeFantasia: 'MOINHO CENTRAL',
        cnpj: '12.345.678/0001-90',
        ie: '123.456.789.000',
        im: '12345678',
        tipoFornecedor: 'Distribuidor',
        situacao: 'Ativo',
        dataCadastro: '2025-01-15',
        contato: { responsavelComercial: 'Giovanni Rossi', telefone: '(11) 3456-7890', whatsapp: '(11) 98765-4321', emailComercial: 'vendas@moinhocentral.com.br', emailFinanceiro: 'financeiro@moinhocentral.com.br', site: 'www.moinhocentral.com.br' },
        endereco: { cep: '01001-000', rua: 'Rua da Itália', numero: '100', complemento: 'Galpão A', bairro: 'Brás', cidade: 'São Paulo', estado: 'SP', pais: 'Brasil' },
        financeiro: { formaPagamento: 'Boleto Bancário', prazoPagamento: '30', limiteCredito: 80000, banco: 'Itaú', agencia: '1234', conta: '98765-0', pix: 'financeiro@moinhocentral.com.br', tipoChavePix: 'E-mail' },
        logistica: { prazoEntrega: '3', diasEntrega: 'Ter, Sex', transportadora: 'TransItalian', pedidoMinimo: 1000, freteMinimo: 100, regiaoAtendimento: 'Sudeste' },
        linkedProducts: [],
        ratings: { qualidade: 10, prazo: 9, atendimento: 9, preco: 8 },
        notes: [],
        history: [],
        blockInfo: { status: 'Ativo', motivo: '' }
    },
    {
        id: 2,
        razaoSocial: 'LATICÍNIOS MANTIQUEIRA LTDA',
        nomeFantasia: 'LATICÍNIO MANTIQUEIRA',
        cnpj: '98.765.432/0001-10',
        ie: '987.654.321.000',
        im: '87654321',
        tipoFornecedor: 'Indústria',
        situacao: 'Ativo',
        dataCadastro: '2025-01-20',
        contato: { responsavelComercial: 'Claudio Lima', telefone: '(35) 3211-5000', whatsapp: '(35) 99111-2233', emailComercial: 'vendas@latmantiqueira.com.br', emailFinanceiro: 'financeiro@latmantiqueira.com.br', site: 'www.latmantiqueira.com.br' },
        endereco: { cep: '37130-000', rua: 'Rodovia das Pias', numero: 'KM 12', complemento: '', bairro: 'Zona Rural', cidade: 'Alfenas', estado: 'MG', pais: 'Brasil' },
        financeiro: { formaPagamento: 'Boleto Bancário', prazoPagamento: '15', limiteCredito: 60000, banco: 'Bradesco', agencia: '3211', conta: '12345-0', pix: '98765432000110', tipoChavePix: 'CNPJ' },
        logistica: { prazoEntrega: '2', diasEntrega: 'Seg, Qui', transportadora: 'Própria', pedidoMinimo: 1500, freteMinimo: 0, regiaoAtendimento: 'Minas Gerais e São Paulo' },
        linkedProducts: [],
        ratings: { qualidade: 9, prazo: 9, atendimento: 8, preco: 8 },
        notes: [],
        history: [],
        blockInfo: { status: 'Ativo', motivo: '' }
    },
    {
        id: 3,
        razaoSocial: 'DISTRIBUIDORA HORTI-PIZZA LTDA',
        nomeFantasia: 'HORTI-PIZZA',
        cnpj: '45.678.901/0001-23',
        ie: '456.789.012.000',
        im: '45678901',
        tipoFornecedor: 'Distribuidor',
        situacao: 'Ativo',
        dataCadastro: '2025-02-10',
        contato: { responsavelComercial: 'Maurício Verde', telefone: '(11) 2712-3000', whatsapp: '(11) 98455-6677', emailComercial: 'comercial@hortipizza.com.br', emailFinanceiro: 'financeiro@hortipizza.com.br', site: '' },
        endereco: { cep: '03010-000', rua: 'Rua do Pomar', numero: '400', complemento: 'Box 12', bairro: 'Vila Maria', cidade: 'São Paulo', estado: 'SP', pais: 'Brasil' },
        financeiro: { formaPagamento: 'Boleto Bancário', prazoPagamento: '7', limiteCredito: 20000, banco: 'Banco do Brasil', agencia: '1200', conta: '99887-1', pix: 'comercial@hortipizza.com.br', tipoChavePix: 'E-mail' },
        logistica: { prazoEntrega: '1', diasEntrega: 'Diariamente', transportadora: 'Própria', pedidoMinimo: 300, freteMinimo: 0, regiaoAtendimento: 'Grande São Paulo' },
        linkedProducts: [],
        ratings: { qualidade: 9, prazo: 10, atendimento: 9, preco: 9 },
        notes: [],
        history: [],
        blockInfo: { status: 'Ativo', motivo: '' }
    },
    {
        id: 4,
        razaoSocial: 'BEBIDAS PAULISTA S/A',
        nomeFantasia: 'BEBIDAS PAULISTA',
        cnpj: '33.222.111/0001-55',
        ie: '332.221.110.000',
        im: '33222111',
        tipoFornecedor: 'Distribuidor',
        situacao: 'Ativo',
        dataCadastro: '2025-01-10',
        contato: { responsavelComercial: 'Fernanda Rocha', telefone: '(11) 4004-9090', whatsapp: '(11) 98122-3344', emailComercial: 'vendas@bebidaspaulista.com.br', emailFinanceiro: 'financeiro@bebidaspaulista.com.br', site: 'www.bebidaspaulista.com.br' },
        endereco: { cep: '07190-100', rua: 'Av. das Indústrias', numero: '500', complemento: 'Galpão 2', bairro: 'Cumbica', cidade: 'Guarulhos', estado: 'SP', pais: 'Brasil' },
        financeiro: { formaPagamento: 'Boleto Bancário', prazoPagamento: '28', limiteCredito: 40000, banco: 'Itaú', agencia: '0530', conta: '77665-4', pix: '33222111000155', tipoChavePix: 'CNPJ' },
        logistica: { prazoEntrega: '2', diasEntrega: 'Seg, Qua, Sex', transportadora: 'Própria', pedidoMinimo: 500, freteMinimo: 0, regiaoAtendimento: 'Sudeste' },
        linkedProducts: [],
        ratings: { qualidade: 9, prazo: 9, atendimento: 9, preco: 7 },
        notes: [],
        history: [],
        blockInfo: { status: 'Ativo', motivo: '' }
    },
    {
        id: 5,
        razaoSocial: 'EMBALAGENS BRASIL LTDA',
        nomeFantasia: 'EMBALAGENS BRASIL',
        cnpj: '23.456.789/0001-01',
        ie: '234.567.890.111',
        im: '23456789',
        tipoFornecedor: 'Fabricante',
        situacao: 'Ativo',
        dataCadastro: '2025-01-30',
        contato: { responsavelComercial: 'Roberto Martins', telefone: '(19) 3880-9000', whatsapp: '(19) 98711-2233', emailComercial: 'vendas@embalagensbrasil.com.br', emailFinanceiro: 'financeiro@embalagensbrasil.com.br', site: 'www.embalagensbrasil.com.br' },
        endereco: { cep: '13040-050', rua: 'Rua do Papelão', numero: '850', complemento: '', bairro: 'Distrito Industrial', cidade: 'Campinas', estado: 'SP', pais: 'Brasil' },
        financeiro: { formaPagamento: 'Boleto Bancário', prazoPagamento: '45', limiteCredito: 30000, banco: 'Santander', agencia: '3211', conta: '12345-0', pix: '23456789000101', tipoChavePix: 'CNPJ' },
        logistica: { prazoEntrega: '4', diasEntrega: 'Qua, Sex', transportadora: 'Jadlog', pedidoMinimo: 800, freteMinimo: 80, regiaoAtendimento: 'Sudeste' },
        linkedProducts: [],
        ratings: { qualidade: 9, prazo: 8, atendimento: 8, preco: 9 },
        notes: [],
        history: [],
        blockInfo: { status: 'Ativo', motivo: '' }
    }
];

export const sectors = [
    { id: 1, name: 'ADMINISTRATIVO E FINANCEIRO', icon: 'fa-briefcase', color: 'color-purple', description: 'Setor administrativo, recursos humanos, financeiro e gerência geral.', status: 'Ativo' },
    { id: 2, name: 'SALÃO E ATENDIMENTO', icon: 'fa-utensils', color: 'color-teal', description: 'Setor de atendimento ao cliente no salão, recepção e coordenação de mesas.', status: 'Ativo' },
    { id: 3, name: 'DELIVERY', icon: 'fa-motorcycle', color: 'color-orange', description: 'Setor de atendimento de pedidos externos e entregas rápidas.', status: 'Ativo' },
    { id: 4, name: 'PRODUÇÃO', icon: 'fa-fire-burner', color: 'color-red', description: 'Setor de preparação de massas, pizzas, molhos e pratos da cozinha.', status: 'Ativo' },
    { id: 5, name: 'BAR', icon: 'fa-wine-bottle', color: 'color-lightblue', description: 'Setor de preparo de drinks, coquetéis e bebidas em geral.', status: 'Ativo' },
    { id: 6, name: 'ESTOQUE E SUPRIMENTOS', icon: 'fa-boxes-stacked', color: 'color-blue', description: 'Setor de recebimento, cotação, compras e controle de insumos.', status: 'Ativo' },
    { id: 7, name: 'SERVIÇOS GERAIS', icon: 'fa-spray-can', color: 'color-green', description: 'Setor de higienização, limpeza e conservação das instalações.', status: 'Ativo' }
];

export const areas = [
    { id: 1, name: 'Gerente de Pizzaria', description: 'Responsável pela administração geral da pizzaria, coordenando equipes, recursos e resultados.', sectorId: 1, status: 'Ativo', userIds: [] },
    { id: 2, name: 'Supervisor de Turno', description: 'Responsável por supervisionar as operações durante seu turno de trabalho.', sectorId: 1, status: 'Ativo', userIds: [] },
    { id: 3, name: 'Analista Administrativo', description: 'Responsável por atividades administrativas e suporte à gestão.', sectorId: 1, status: 'Ativo', userIds: [] },
    { id: 4, name: 'Assistente Financeiro', description: 'Responsável pelo apoio às rotinas financeiras da empresa.', sectorId: 1, status: 'Ativo', userIds: [] },
    { id: 5, name: 'Maître', description: 'Responsável pela coordenação do salão e supervisão da equipe de atendimento.', sectorId: 2, status: 'Ativo', userIds: [] },
    { id: 6, name: 'Recepcionista', description: 'Responsável pela recepção e organização da entrada dos clientes.', sectorId: 2, status: 'Ativo', userIds: [] },
    { id: 7, name: 'Garçom', description: 'Responsável pelo atendimento direto aos clientes nas mesas.', sectorId: 2, status: 'Ativo', userIds: [] },
    { id: 8, name: 'Cumim', description: 'Auxilia os garçons e apoia a organização do salão.', sectorId: 2, status: 'Ativo', userIds: [] },
    { id: 9, name: 'Operador de Caixa', description: 'Responsável pelo controle das vendas e recebimentos da pizzaria.', sectorId: 2, status: 'Ativo', userIds: [] },
    { id: 10, name: 'Atendente de Delivery', description: 'Responsável pelo recebimento e acompanhamento dos pedidos de entrega.', sectorId: 3, status: 'Ativo', userIds: [] },
    { id: 11, name: 'Entregador', description: 'Responsável pela entrega dos pedidos aos clientes.', sectorId: 3, status: 'Ativo', userIds: [] },
    { id: 12, name: 'Pizzaiolo', description: 'Responsável pela preparação e finalização das pizzas.', sectorId: 4, status: 'Ativo', userIds: [] },
    { id: 13, name: 'Auxiliar de Pizzaiolo', description: 'Auxilia o pizzaiolo na produção das pizzas.', sectorId: 4, status: 'Ativo', userIds: [] },
    { id: 14, name: 'Cozinheiro', description: 'Responsável pelo preparo dos pratos e produtos da cozinha.', sectorId: 4, status: 'Ativo', userIds: [] },
    { id: 15, name: 'Auxiliar de Cozinha', description: 'Presta apoio às atividades da cozinha.', sectorId: 4, status: 'Ativo', userIds: [] },
    { id: 16, name: 'Barman', description: 'Responsável pela preparação e serviço de bebidas.', sectorId: 5, status: 'Ativo', userIds: [] },
    { id: 17, name: 'Auxiliar de Bar', description: 'Auxilia as atividades operacionais do bar.', sectorId: 5, status: 'Ativo', userIds: [] },
    { id: 18, name: 'Estoquista', description: 'Responsável pelo controle e armazenamento de materiais e insumos.', sectorId: 6, status: 'Ativo', userIds: [] },
    { id: 19, name: 'Comprador', description: 'Responsável pelas aquisições da empresa.', sectorId: 6, status: 'Ativo', userIds: [] },
    { id: 20, name: 'Auxiliar de Limpeza', description: 'Responsável pela limpeza e conservação das instalações.', sectorId: 7, status: 'Ativo', userIds: [] }
];

export const stockBatches = [
    { id: 1, itemSku: "MAS-001", lot: "LT-1001", brand: "Le 5 Stagioni", supplier: "MOINHO CENTRAL", manufacturingDate: "2026-05-10", expirationDate: "2026-11-10", address: "ESA-01-01", quantity: 100, unit: "KG" },
    { id: 2, itemSku: "MAS-001", lot: "LT-1002", brand: "Le 5 Stagioni", supplier: "MOINHO CENTRAL", manufacturingDate: "2026-05-20", expirationDate: "2026-11-20", address: "ESA-01-02", quantity: 50, unit: "KG" },
    { id: 3, itemSku: "MAS-002", lot: "LT-1003", brand: "Fermipan", supplier: "MOINHO CENTRAL", manufacturingDate: "2026-05-01", expirationDate: "2026-11-01", address: "ESB-01-01", quantity: 8, unit: "KG" },
    { id: 4, itemSku: "LAC-001", lot: "LT-2001", brand: "Mantiqueira", supplier: "LATICÍNIO MANTIQUEIRA", manufacturingDate: "2026-05-15", expirationDate: "2026-07-15", address: "CFA-01-01", quantity: 80, unit: "KG" },
    { id: 5, itemSku: "LAC-001", lot: "LT-2002", brand: "Mantiqueira", supplier: "LATICÍNIO MANTIQUEIRA", manufacturingDate: "2026-05-25", expirationDate: "2026-07-25", address: "CFA-01-02", quantity: 40, unit: "KG" },
    { id: 6, itemSku: "MOL-001", lot: "LT-3001", brand: "La Molisana", supplier: "HORTI-PIZZA", manufacturingDate: "2026-04-10", expirationDate: "2027-04-10", address: "ESA-02-01", quantity: 65, unit: "KG" },
    { id: 7, itemSku: "PRO-001", lot: "LT-4001", brand: "Sadia", supplier: "LATICÍNIO MANTIQUEIRA", manufacturingDate: "2026-05-01", expirationDate: "2026-08-01", address: "CFA-02-01", quantity: 45, unit: "KG" },
    { id: 8, itemSku: "PRO-002", lot: "LT-4002", brand: "Perdigão", supplier: "LATICÍNIO MANTIQUEIRA", manufacturingDate: "2026-05-05", expirationDate: "2026-08-05", address: "CFA-02-02", quantity: 30, unit: "KG" },
    { id: 9, itemSku: "PRO-003", lot: "LT-4003", brand: "Seara", supplier: "LATICÍNIO MANTIQUEIRA", manufacturingDate: "2026-05-10", expirationDate: "2026-09-10", address: "CFA-02-03", quantity: 25, unit: "KG" },
    { id: 10, itemSku: "PRO-004", lot: "LT-4004", brand: "Copacol", supplier: "LATICÍNIO MANTIQUEIRA", manufacturingDate: "2026-05-12", expirationDate: "2026-09-12", address: "CFA-02-04", quantity: 35, unit: "KG" },
    { id: 11, itemSku: "LAC-002", lot: "LT-2003", brand: "Scala", supplier: "LATICÍNIO MANTIQUEIRA", manufacturingDate: "2026-05-10", expirationDate: "2026-08-10", address: "CFA-01-03", quantity: 25, unit: "UN" },
    { id: 12, itemSku: "LAC-003", lot: "LT-2004", brand: "Faixa Azul", supplier: "LATICÍNIO MANTIQUEIRA", manufacturingDate: "2026-04-20", expirationDate: "2026-10-20", address: "CFA-01-04", quantity: 15, unit: "KG" },
    { id: 13, itemSku: "LAC-004", lot: "LT-2005", brand: "Cruzilia", supplier: "LATICÍNIO MANTIQUEIRA", manufacturingDate: "2026-05-01", expirationDate: "2026-08-01", address: "CFA-01-05", quantity: 12, unit: "KG" },
    { id: 14, itemSku: "LAC-005", lot: "LT-2006", brand: "President", supplier: "LATICÍNIO MANTIQUEIRA", manufacturingDate: "2026-04-15", expirationDate: "2026-10-15", address: "CFA-01-06", quantity: 15, unit: "KG" },
    { id: 15, itemSku: "HOR-001", lot: "LT-5001", brand: "Horti-Pizza", supplier: "HORTI-PIZZA", manufacturingDate: "2026-06-01", expirationDate: "2026-06-15", address: "CFA-03-01", quantity: 40, unit: "KG" },
    { id: 16, itemSku: "HOR-002", lot: "LT-5002", brand: "Horti-Pizza", supplier: "HORTI-PIZZA", manufacturingDate: "2026-06-01", expirationDate: "2026-06-20", address: "CFA-03-02", quantity: 20, unit: "KG" },
    { id: 17, itemSku: "HOR-003", lot: "LT-5003", brand: "Horti-Pizza", supplier: "HORTI-PIZZA", manufacturingDate: "2026-06-01", expirationDate: "2026-06-20", address: "CFA-03-03", quantity: 30, unit: "KG" },
    { id: 18, itemSku: "HOR-004", lot: "LT-5004", brand: "Horti-Pizza", supplier: "HORTI-PIZZA", manufacturingDate: "2026-06-03", expirationDate: "2026-06-10", address: "CFA-03-04", quantity: 15, unit: "UN" },
    { id: 19, itemSku: "HOR-005", lot: "LT-5005", brand: "Horti-Pizza", supplier: "HORTI-PIZZA", manufacturingDate: "2026-06-03", expirationDate: "2026-06-10", address: "CFA-03-05", quantity: 18, unit: "UN" },
    { id: 20, itemSku: "HOR-006", lot: "LT-5006", brand: "Horti-Pizza", supplier: "HORTI-PIZZA", manufacturingDate: "2026-05-15", expirationDate: "2026-08-15", address: "ESB-02-01", quantity: 10, unit: "KG" },
    { id: 21, itemSku: "HOR-007", lot: "LT-5007", brand: "Vale Fértil", supplier: "HORTI-PIZZA", manufacturingDate: "2026-05-10", expirationDate: "2027-05-10", address: "ESA-02-02", quantity: 25, unit: "KG" },
    { id: 22, itemSku: "TMP-001", lot: "LT-6001", brand: "Andorinha", supplier: "MOINHO CENTRAL", manufacturingDate: "2026-04-01", expirationDate: "2027-04-01", address: "ESA-03-01", quantity: 24, unit: "UN" },
    { id: 23, itemSku: "TMP-002", lot: "LT-6002", brand: "Kitano", supplier: "MOINHO CENTRAL", manufacturingDate: "2026-05-01", expirationDate: "2027-05-01", address: "ESB-02-02", quantity: 5, unit: "KG" },
    { id: 24, itemSku: "TMP-003", lot: "LT-6003", brand: "Cisne", supplier: "MOINHO CENTRAL", manufacturingDate: "2026-05-01", expirationDate: "2028-05-01", address: "ESB-02-03", quantity: 10, unit: "UN" },
    { id: 25, itemSku: "BEB-001", lot: "LT-7001", brand: "Coca-Cola", supplier: "BEBIDAS PAULISTA", manufacturingDate: "2026-05-20", expirationDate: "2026-11-20", address: "ESA-04-01", quantity: 60, unit: "UN" },
    { id: 26, itemSku: "BEB-002", lot: "LT-7002", brand: "Antarctica", supplier: "BEBIDAS PAULISTA", manufacturingDate: "2026-05-20", expirationDate: "2026-11-20", address: "ESA-04-02", quantity: 50, unit: "UN" },
    { id: 27, itemSku: "BEB-003", lot: "LT-7003", brand: "Ambev", supplier: "BEBIDAS PAULISTA", manufacturingDate: "2026-05-15", expirationDate: "2026-11-15", address: "ESA-04-03", quantity: 120, unit: "UN" },
    { id: 28, itemSku: "BEB-004", lot: "LT-7004", brand: "Crystal", supplier: "BEBIDAS PAULISTA", manufacturingDate: "2026-05-25", expirationDate: "2027-05-25", address: "ESA-04-04", quantity: 80, unit: "UN" },
    { id: 29, itemSku: "EMB-001", lot: "LT-8001", brand: "Embalagens Brasil", supplier: "EMBALAGENS BRASIL", manufacturingDate: "2026-05-01", expirationDate: "2028-05-01", address: "ESB-03-01", quantity: 300, unit: "UN" },
    { id: 30, itemSku: "EMB-002", lot: "LT-8002", brand: "Embalagens Brasil", supplier: "EMBALAGENS BRASIL", manufacturingDate: "2026-05-01", expirationDate: "2028-05-01", address: "ESB-03-02", quantity: 250, unit: "UN" },
    { id: 31, itemSku: "LIM-001", lot: "LT-9001", brand: "Clean Química", supplier: "EMBALAGENS BRASIL", manufacturingDate: "2026-05-01", expirationDate: "2027-05-01", address: "ESB-04-01", quantity: 15, unit: "UN" },
    { id: 32, itemSku: "LIM-002", lot: "LT-9002", brand: "Clean Química", supplier: "EMBALAGENS BRASIL", manufacturingDate: "2026-05-01", expirationDate: "2027-05-01", address: "ESB-04-02", quantity: 8, unit: "UN" }
];
